### ISSUE TITLE
scale date commands for plots stopped working

### ISSUE THREAD

**Issue by joanaleite** [tidyverts/feasts#108]
The scale date commands stopped working with the recent update. The error reported is that it "works with objects of class Date only". I detected this problem with autoplot() and gg-season().

> library(fpp3)
> aus_production %>% autoplot(Beer) + scale_x_date(date_breaks = "5 year", date_labels = "%Y")
Error: Invalid input: date_trans works with objects of class Date only

**Comment by mitchelloharawild** [comment]
This is a change introduced by tsibble v0.9.0.
You will need to use `scale_x_yearmonth()` for data that is of `yearmonth` type.
