### ISSUE TITLE
gg_season() for annual data

### ISSUE THREAD

**Issue by earowang** [tidyverts/feasts#111]
Should the series of `1821` start at 0 instead of 21?

``` r
library(feasts)
#> Loading required package: fabletools
lynx_tsbl <- as_tsibble(lynx)
gg_season(lynx_tsbl, value, period = "40 year")
```

![](https://i.imgur.com/cJQDffI.png)

``` r
forecast::seasonplot(lynx, 40, type = "l")
#> Registered S3 method overwritten by 'quantmod':
#>   method            from
#>   as.zoo.data.frame zoo
```

![](https://i.imgur.com/SzXqtIm.png)

<sup>Created on 2020-07-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by robjhyndman** [comment]
I think it is simpler to interpret when starting at 1.

**Comment by mitchelloharawild** [comment]
Yes, it should start at 1.

**Comment by mitchelloharawild** [comment]
``` r
library(feasts)
#> Loading required package: fabletools
lynx_tsbl <- as_tsibble(lynx)
gg_season(lynx_tsbl, value, period = "40 year")
```

![](https://i.imgur.com/4rwBFMa.png)

<sup>Created on 2020-07-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by earowang** [comment]
The x-axis values are not expected, akin to other relevant issues.

Cheers,
Earo
