### ISSUE TITLE
unitroot_nsdiffs() is misnamed

### ISSUE THREAD

**Issue by robjhyndman** [tidyverts/feasts#119]
It does not use unit roots for the number of seasonal differences.

**Comment by mitchelloharawild** [comment]
`unitroot_nsdiffs()` provides the repeated testing procedure for identifying the number of differences required to achieve stationarity.
It doesn't enforce the seasonal strength test to be used, however the default is based on the seasonal strength.

I think some clarification regarding the default test for `unitroot_nsdiffs()` is required, and some guidance on using alternative tests.
