### ISSUE TITLE
Components with x11 special for X_13ARIMA_SEATS

### ISSUE THREAD

**Issue by EconProf** [tidyverts/feasts#128]
components() works fine for a fitted X_13ARIMA_SEATS model but not with the x11 special. As usual, user error may be involved.

fable 0.3.0.9000
feasts 0.2.0.9000
fabletools 0.3.1.9000

``` r
library(fpp3)

fit11 <- tsibbledata::aus_production %>%
  model(X_13ARIMA_SEATS(Beer ~ x11()))
components(fit11)
#> Error: Problem with `mutate()` input `cmp`.
#> x argument is of length zero
#> ℹ Input `cmp` is `map(.fit, components)`.
```

<sup>Created on 2021-03-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by mitchelloharawild** [comment]
Thanks, this is fixed in https://github.com/tidyverts/feasts/commit/a2a621ca07fc0595fb2e3d2af579a0342ff9c214
I have a patch waiting for CRAN acceptance now.

**Comment by mitchelloharawild** [comment]
On CRAN now.
