### ISSUE TITLE
question about gg_tsdisplay function

### ISSUE THREAD

**Issue by rbelmontelopes** [tidyverts/feasts#138]
Is there a way to make gg_tsdisplay() x axis of the first plot (time series) start on the date of the first sample? 
In my case the first sample starts on day 2, but the plot starts on day one (the period in the tsibble is 7D)

Additionally, there is a way to to make this time series plot show the dates for all samples instead of one date for each 15 days?

Thanks for your time,

Best Regards

Ricardo

**Comment by mitchelloharawild** [comment]
Do you have an example dataset to better describe what you would like to make?
If you save the gg_tsdisplay output, you are able to modify each individual plot.

For example,
``` r
library(feasts)
#> Loading required package: fabletools
library(ggplot2)
p <- gg_tsdisplay(tsibbledata::aus_production, Beer)
p[[1]] <- p[[1]] + geom_point()
p
```

![](https://i.imgur.com/Hc7oI8r.png)

<sup>Created on 2021-06-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
