### ISSUE TITLE
autoplot() for decompositions: default black for one key

### ISSUE THREAD

**Issue by earowang** [tidyverts/feasts#15]
Can we default to black line when only one key?
``` r
library(feasts)
library(tsibble) 
#> 
#> Attaching package: 'tsibble'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
pedestrian %>% 
  filter(Sensor == "Southern Cross Station") %>% 
  STL(Count) %>% 
  autoplot()
```

![](https://i.imgur.com/ctJTXxr.png)

<sup>Created on 2019-02-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by earowang** [comment]
Can we move the scale bar to the left?

**Comment by mitchelloharawild** [comment]
Scale bar to the left is a separate issue and more of a design choice.
@robjhyndman - any preference on this?

**Comment by robjhyndman** [comment]
I think it probably works better when the bar is close to the scale. So on the left might be better.
