### ISSUE TITLE
feasts dependencies error on CRAN

### ISSUE THREAD

**Issue by feng-li** [tidyverts/feasts#163]
I just noticed the dependence chain on CRAN for `feasts` breaks, https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/feasts-00check.html

which caused other packages a build fail

https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/gratis-00check.html

**Comment by mitchelloharawild** [comment]
Thanks, and sorry!
I'll be pushing a quick fix for fabletools which should solve these issues shortly.

**Comment by mitchelloharawild** [comment]
An update to fabletools has now been accepted on CRAN which I hope resolves these downstream issues.
Let me know if you're still having trouble with this.
