### ISSUE TITLE
Inconsistent missing values in gg_lag

### ISSUE THREAD

**Issue by robjhyndman** [tidyverts/feasts#29]
``` r
library(tsibbledata)
library(feasts)
#> 
#> Attaching package: 'feasts'
#> The following object is masked from 'package:grDevices':
#> 
#>     X11

aus_production %>% gg_lag(Bricks)
#> Warning: Removed 20 rows containing missing values (geom_path).
```

![](https://i.imgur.com/O3Ftfx6.png)

``` r

aus_production %>% gg_lag(Bricks, geom='point')
#> Warning: Removed 180 rows containing missing values (geom_point).
```

![](https://i.imgur.com/EvJQT5x.png)

<sup>Created on 2019-03-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mitchelloharawild** [comment]
This was fixed during class today.

**Comment by mitchelloharawild** [comment]
The error is correct, albeit confusing. `gg_lag()` now has a custom error for missing values.
https://github.com/tidyverts/feasts/commit/6ae5eb3c608aa249b387ca119af2aeafacf2f2bc
