### ISSUE TITLE
tsfeatures

### ISSUE THREAD

**Issue by robjhyndman** [tidyverts/feasts#3]
Perhaps pull in the features that are implemented in tsfeatures?

Also, I think STL should probably be moved to tsibblestats rather than live in fable.

Finally, perhaps tsibblestats should have features in its name? Perhaps feasts (FEatures And Statistics for Time Series)

**Comment by mitchelloharawild** [comment]
Closing in favour of #22

1. Yes, features should be in feasts (#22)
2. Done
3. Done
