### ISSUE TITLE
gg_season and max_cols

### ISSUE THREAD

**Issue by robjhyndman** [tidyverts/feasts#30]
I'm not sure the current defaults are right.  For example

```r
tsibbledata::PBS %>%
  filter(ATC2 == "A10") %>%
  summarise(Cost = sum(Cost)/1e6) %>%
  gg_season(Cost, labels = "both") +
    ylab("$ million") +
    ggtitle("Seasonal plot: antidiabetic drug sales")
```

is black and white, but there is no reason it should not be full colour given the legend is suppressed.

**Comment by mitchelloharawild** [comment]
I've fixed the issue relating to labels, however I think the interface for this can still be improved.
For example, it may be useful to convert to a continuous scale at some point.

**Comment by mitchelloharawild** [comment]
Change from discrete to continuous.. somehow maintain hue colours.

**Comment by mitchelloharawild** [comment]
``` r
library(feasts)
#> 
#> Attaching package: 'feasts'
#> The following object is masked from 'package:grDevices':
#> 
#>     X11
tsibbledata::aus_production %>% 
  gg_season(Cement, max_col = 100)
#> Error in guides(colour = guide_legend()): could not find function "guides"
tsibbledata::aus_production %>% 
  gg_season(Cement)
```

![](https://i.imgur.com/Gce6crS.png)

<sup>Created on 2019-05-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
