### ISSUE TITLE
ndiffs inconsistency with forecast

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/feasts#40]
``` r
library(feasts)
#> 
#> Attaching package: 'feasts'
#> The following object is masked from 'package:grDevices':
#> 
#>     X11
as_tsibble(WWWusage) %>% 
  features(value, unitroot_ndiffs)
#> # A tibble: 1 x 1
#>   value_ndiffs
#>          <int>
#> 1            0
forecast::ndiffs(WWWusage)
#> [1] 1
```

<sup>Created on 2019-04-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mitchelloharawild** [comment]
@robjhyndman This is due to the default lag choice in `urca::ur.kpss()`.

forecast uses the old tseries default of `trunc(3*sqrt(length(x))/13)`, and fable uses the current urca default of `trunc(4 * (n/100)^0.25)`.

Relevant discussions:
* tseries change of default: https://cran.r-project.org/web/packages/tseries/ChangeLog
* forecast (reverted) change of use.lag: https://github.com/robjhyndman/forecast/commit/6c86c6390beb6f0007d13926ce486e7a63ebf9f4

**Comment by robjhyndman** [comment]
Hmm. Another example where the urca defaults lead to a clearly incorrect result.
