### ISSUE TITLE
Add title to gg_tsdisplay

### ISSUE THREAD

**Issue by robjhyndman** [tidyverts/feasts#46]
Is there a way to add a title? The function does not return a ggplot2 object, so + ggtitle() does not work.

**Comment by mitchelloharawild** [comment]
I don't know what the best way to achieve this is. Adding arguments like done in `forecast` is the easy way, however it would be inconsistent with the rest of the plotting functions in `feasts`.

Suppose it's possible to implement this, what would you expect from the following code:
`gg_tsdisplay() + ggtitle()`
`gg_tsdisplay() + geom_point(colour = "red")`
`gg_tsdisplay() + coord_flip()`

**Comment by mitchelloharawild** [comment]
ggplot2 elements added to `gg_tsdisplay()` will now be added to the first plot.
