### ISSUE TITLE
Feature naming

### ISSUE THREAD

**Issue by earowang** [tidyverts/feasts#60]
Roughly they are model, tests, data driven features?

* If model, are they coefficients (`coef_*`) or diagnostics (`diag_`)?
* If tests, are they p-values `pvalue_*` or test statistics `test_stat_*`?
* If data, are they overall `const_*`, rolling `roll_`, partitioning `par_`, cumulative `cum_`?

**Comment by mitchelloharawild** [comment]
Is this for naming the feature functions, or the output column names?

**Comment by earowang** [comment]
Both.

**Comment by earowang** [comment]
I think many individual functions should live in a different package, but keep `acf_*`, `diff_*`, `unitroot_` and `stl_*` in.

For some sliding features, probably better to use **RcppRoll** to compute.

**Comment by mitchelloharawild** [comment]
Are you referring to compengine/hctsa features?
I think many of the features in tsfeatures can be included in feasts, and that feasts should provide a basic set of useful features. More specialised features, or features from other libraries (`hctsa`, `tsfresh`) can be set up in different packages.

**Comment by earowang** [comment]
compengine/hctsa features as well as sliding features. `max_*` are useful but they need to be faster using RcppRoll, tsibble's `slide_*` is slow for this specific task.

Feature names (both functions and vector names) need to be standardised before releasing. If some functions we can't find good names for, should be separated to a different package or next release.

**Comment by mitchelloharawild** [comment]
As for RcppRoll, I'm happy to have slow versions in the first release as this will not result in a breaking change later.

Do you think it is reasonable to have a whole package around sliding features? I think it's better that they are included in feasts, and later introduce a RcppRoll suggest for a speed improvement (with fallback to tsibble).

**Comment by mitchelloharawild** [comment]
@earowang 
I've renamed a bunch of the functions and outputs. Could you please review these?

**Comment by earowang** [comment]
* `crossing_points` -> `n_crossing_points`
* `flat_spots` -> `n_flat_spots`
* `_pval` -> `_pvalue`
* `seas` -> `season`
* `features_` -> `feat_`

**Comment by earowang** [comment]
https://github.com/tidyverts/feasts/blob/bfe3e99ffe23754bc3052684730ca4e5e2bcddf5/R/features.R#L504

remove `x`

**Comment by mitchelloharawild** [comment]
How does everything look now?

**Comment by earowang** [comment]
Defunct instead of deprecate before CRAN

https://github.com/tidyverts/feasts/blob/44ecc82ae6b8e392278062be30fc2b88b0d2cbf1/R/features.R#L99

https://github.com/tidyverts/feasts/blob/44ecc82ae6b8e392278062be30fc2b88b0d2cbf1/R/features.R#L321

`time_kl_shift` -> `shift_kl_index`?

https://github.com/tidyverts/feasts/blob/44ecc82ae6b8e392278062be30fc2b88b0d2cbf1/R/features.R#L381

Are they `roll`ing? You used `tile_` in the function. You need to update the output names as well

**Comment by mitchelloharawild** [comment]
1. Will remove all deprecated things before CRAN.
2. Mistake, yes.
3. `roll` is more generic than `tile`. I'm happy to use `tile` though.

**Comment by earowang** [comment]
I thought `shift` -> `roll` & `roll` -> `tile`

**Comment by mitchelloharawild** [comment]
Why `roll` not `slide`?

**Comment by earowang** [comment]
I prefer `partition` over `tile`.

**Comment by mitchelloharawild** [comment]
So `roll` -> `partition`.
I don't particularly like `partition` (or `lumpiness` for that matter... what does it mean for a time series). To me, `partition` gives me the ideas that you're partitioning the `lumpiness`, rather than computing `lumpiness` on `partition`s of the data. `lumpiness` seems too general for a single method, instead it seems better to treat it as a tag.

**Comment by earowang** [comment]
`lumpiness` and `stability` are too generic, I agree. I don't have better ideas on renaming them.

**Comment by mitchelloharawild** [comment]
`var_tiled_var`, `mean_tiled_var`?

**Comment by earowang** [comment]
Although I laughed, we could go for them.

**Comment by mitchelloharawild** [comment]
Boring, yes. Descriptive, yes. I think naming for feature functions and outputs should be self-descriptive, and the tags should be interesting. Anything against those names?

**Comment by earowang** [comment]
Sounds good.

**Comment by mitchelloharawild** [comment]
All updated. Anything else?

**Comment by earowang** [comment]
https://github.com/tidyverts/feasts/blob/7258b234ee022b4cb567f4bd0c1698cd2610a533/R/features.R#L29

I'm not sure if this is `stat_arch_lm`

**Comment by mitchelloharawild** [comment]
Fixed.

**Comment by earowang** [comment]
https://github.com/tidyverts/feasts/blob/7258b234ee022b4cb567f4bd0c1698cd2610a533/R/features.R#L91

spike or spikeness?

**Comment by mitchelloharawild** [comment]
`spikiness`.

**Comment by mitchelloharawild** [comment]
Or `var_loo`?

**Comment by earowang** [comment]
yes. `var_loo`.

**Comment by mitchelloharawild** [comment]
Looking at the code, I actually think it's more like `var_var_loo` :laughing:

**Comment by earowang** [comment]
okay. spikiness then.

**Comment by earowang** [comment]
I like that measure. it works great.

**Comment by earowang** [comment]
🎉 👏
