### ISSUE TITLE
auto naming of columns based on functions passed?

### ISSUE THREAD

**Issue by njtierney** [tidyverts/feasts#64]
At the moment the column name is given as `V1` if a function is passed, otherwise a named list will rectify this. I'm not sure if it's worth it, but I was thinking it might be nice to have some auto-naming of columns if a named list is not provided. 

So ideally the first function would return the same output as the second.

What do you think? 

``` r
library(brolgar)

world_heights %>%
  features(height_cm,
           min)
#> # A tibble: 153 x 2
#>    country        V1
#>    <chr>       <dbl>
#>  1 Afghanistan  161.
#>  2 Albania      168.
#>  3 Algeria      166.
#>  4 Angola       159.
#>  5 Argentina    167.
#>  6 Armenia      164.
#>  7 Australia    170 
#>  8 Austria      162.
#>  9 Azerbaijan   170.
#> 10 Bahrain      161.
#> # … with 143 more rows

world_heights %>%
  features(height_cm,
           list(min = min))
#> # A tibble: 153 x 2
#>    country       min
#>    <chr>       <dbl>
#>  1 Afghanistan  161.
#>  2 Albania      168.
#>  3 Algeria      166.
#>  4 Angola       159.
#>  5 Argentina    167.
#>  6 Armenia      164.
#>  7 Australia    170 
#>  8 Austria      162.
#>  9 Azerbaijan   170.
#> 10 Bahrain      161.
#> # … with 143 more rows
```

<sup>Created on 2019-07-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mitchelloharawild** [comment]
autonaming is not supported by the current interface, as it is not being pursued by tidyverse for these types of functions. I agree that it would be nice, but for now I think it is best to use `V1` (or `..1`) as the default names.

**Comment by earowang** [comment]
I think the default name should be the function name `min`, the same as `summarise(df, min(x))`. Alternatively, `features()` gains a new argument `.name_repair()` as the one in `tibble()`.

**Comment by mitchelloharawild** [comment]
Use `tibble::lst()` for automatic naming.
