### ISSUE TITLE
Should gg_tsdisplay have plot_type='histogram' as default?

### ISSUE THREAD

**Issue by robjhyndman** [tidyverts/feasts#68]
The most common use for this function is to look at residuals, and then the histogram is more useful than the PACF. Also, the use of ACF/PACF to pick an ARIMA model is largely about legacy rather than modern best practice, so perhaps it is time to retire it as a default.

**Comment by mitchelloharawild** [comment]
I'd think that the default should be an ensemble of plots that best display the features of the time series. Perhaps gg_tsdisplay should be more dynamic and show plots of seasonality when appropriate.

I think residual time series require a very different ensemble of graphics than the response time series, and so a separate function may be more appropriate here.

**Comment by robjhyndman** [comment]
OK. If we have a separate residuals function that wraps a particular form of gg_tsdisplay(), perhaps it should take the mable as the argument and generate residuals on the fly like `forecast:::checkresiduals()` does?

**Comment by mitchelloharawild** [comment]
Is there any extra information from the mable other than the residuals which would need to be used for the graphic?

**Comment by robjhyndman** [comment]
I don't think so

**Comment by mitchelloharawild** [comment]
Hmm - I'm torn for what is the best approach here.
I think two functions is a good idea, but the ensemble of plots in `gg_tsdisplay` and `gg_???`  need further thinking.

What plots would you want to see when looking at a time series? How does this change based on the characteristics of the data? What if it is seasonal or multi-seasonal?
* Time plot
* Plots of time series structures (trend, seasonality, autocorrelation, etc?)

What plots should be looked at when checking the residuals?
* Time plot
* ACF
* Histogram
* more?

**Comment by robjhyndman** [comment]
For a non-seasonal time series, probably a time plot, ACF, and either spectrum or histogram.
For a seasonal time series with one period, probably time plot, ACF and season plot
For a seasonal time series with multiple periods, I'm not sure. I don't think this has been thought about sufficiently in the literature or in practice.
For residuals, a time plot, acf and histogram.

**Comment by mitchelloharawild** [comment]
Any suggestions for an appropriate name of the residual plot function?
`gg_tsresid`, `gg_residuals`, `gg_residualdisplay()`...

**Comment by robjhyndman** [comment]
How about `gg_tsresiduals()` so we don't step on any other non-time series applications.
