### ISSUE TITLE
gg_tsdisplay failing with differenced data or NAs due to spectrum

### ISSUE THREAD

**Issue by JoseAntonioOrtega** [tidyverts/feasts#76]
One of the main uses of gg_tsdisplay is to identify the different behaviour of differenced series. Well, spectrum calculation seems to require no NAs and the default gg_tsdisplay for annual data gives an error. This could be avoided by removing the NAs introduced by differentiation prior to spectrum calculation.

Reproducible example:
```
tsibble(
date = 1990:1999,
value = rnorm(10),index=date
) %>% mutate(dvalue=difference(value)) %>% gg_tsdisplay(dvalue)
```
Error in na.fail.default(as.ts(x)) : missing values in object

In contrast
`tsibble(
date = 1990:1999,
value = rnorm(10),index=date
) %>% mutate(dvalue=difference(value)) %>% gg_tsdisplay(dvalue,plot_type="partial")`

works fine.

**Comment by mitchelloharawild** [comment]
Thanks, fixed.
