### ISSUE TITLE
Is there a plot function with similar capabilities to forecast::ggsubseriesplot(AirPassengers)?

### ISSUE THREAD

**Issue by drorberel** [tidyverts/feasts#83]
I noticed feasts::gg_subseries(), but I am not interested in the facet grid

**Comment by robjhyndman** [comment]
`gg_subseries()` is the replacement for `forecast::ggsubseriesplot()`. If you don't like our design choices, you will need to write your own function.

**Comment by mitchelloharawild** [comment]
Closing as `feasts::gg_subseries()` is the equivalent to `forecast::ggsubseriesplot()`.
The plotting functions are designed to easily/quickly produce common time series graphics, and for any further customisation we recommend constructing your own graphics with ggplot2.

Happy to discuss the appropriateness of facets in this application if you feel strongly about this.
