### ISSUE TITLE
STL

### ISSUE THREAD

**Issue by Nicky9529** [tidyverts/feasts#86]
Hi

When I try to use the STL function on a tsibble, I get this error message:

_A model specification is trained to a dataset using the `model()` function.
Refer to the documentation in ?model for more details._

**Comment by mitchelloharawild** [comment]
Kindly refer to the NEWS. There is a breaking change with decompositions in the v0.1.2 release.
https://feasts.tidyverts.org/news/index.html

> Decompositions are now treated as models. To access the decomposed values, you will now have to use `components()`. For example, `tourism %>% STL(Trips)` is now `tourism %>% model(STL(Trips)) %>% components()`. This change allows for more flexible decomposition specifications, and better interfaces for decomposition modelling.
