### ISSUE TITLE
Parameter error in gg_season calling scale_x_date

### ISSUE THREAD

**Issue by ecoughlan** [tidyverts/feasts#88]
I believe [this change](https://github.com/tidyverts/feasts/commit/652d6ea1948f19121e6d9700510f245d93d7103d#diff-6f327c3c21833fe1b104fae42852db90R241) introduced the following error when the if branch is taken:
`Error in ggplot2::scale_x_date()$trans$breaks(limit, n = len) : 
  unused argument (n = len)`
which was probably copied from the similar `scale_x_datetime()` below. Removing `n = len` I can plot again.
Edit: I assumed wrong, I get the same error on scale_x_datetime(), maybe this is just a version incompatibility.

**Comment by mitchelloharawild** [comment]
Please update the scales package to the latest CRAN version. I didn't
realise this version dependency before submitting the latest version to
CRAN, but it is correctly stated in the dev version.

**Comment by ecoughlan** [comment]
Confirmed, with scales 1.1.0 everything works. :+1:
