### ISSUE TITLE
Trouble with difference()

### ISSUE THREAD

**Issue by GeorgeAthana** [tidyverts/feasts#89]
sheep <- as_tsibble(fma::sheep)
sheep %>% gg_tsdisplay(difference(value))

If NA is the problem with the spectrum calculation it is removed when setting plot_type to 'partial'
sheep %>% gg_tsdisplay(difference(value), plot_type = 'partial')

**Comment by mitchelloharawild** [comment]
If the data to be plotted contains missing values, should a different plot be shown or the missing values handled in some way?

**Comment by GeorgeAthana** [comment]
Hmm. I don't have a preference. Maybe a warning (that spectrum cannot be calculated due to missing value) leaving the user to deal with it and plotting only the ACF in that case. The current warning is good. 

Warning messages:
1: Removed 1 rows containing missing values (geom_path). 
2: Removed 1 rows containing missing values (geom_point).

**Comment by mitchelloharawild** [comment]
Here's what I've got now - let me know if you think anything needs changing.

``` r
library(feasts)
#> Loading required package: fabletools
sheep <- as_tsibble(fma::sheep)
#> Registered S3 method overwritten by 'quantmod':
#>   method            from
#>   as.zoo.data.frame zoo
sheep %>% gg_tsdisplay(value)
```

![](https://i.imgur.com/EoYhrJV.png)

``` r
sheep %>% gg_tsdisplay(difference(value))
#> Warning: Spectrum plot could not be shown as the data contains missing values.
#> Consider using a different `plot_type`.
#> Warning: Removed 1 rows containing missing values (geom_path).
#> Warning: Removed 1 rows containing missing values (geom_point).
```

![](https://i.imgur.com/bemu78H.png)

<sup>Created on 2020-02-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
