### ISSUE TITLE
Add features for intermittency

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/feasts#93]
cc @robjhyndman 

Any well known features that should be included for this, or should I make some up?

**Comment by robjhyndman** [comment]
The two that are used in the literature (Kostenko & Hyndman 2006: [doi.org/10.1057/palgrave.jors.2602211](https://doi.org/10.1057/palgrave.jors.2602211))
 * p = average interval between non-zero observations
 * v = squared coefficient of variation of non-zero observations

You could probably also add proportion of zeros in the time series

**Comment by mitchelloharawild** [comment]
Great, I was considering something with `rle` which should be equivalent to `p`.

What do you think about the proportion of the series starting/ending with 0. In sales data, this may indicate if a product has been phased in or out.

**Comment by robjhyndman** [comment]
Yes, that could also be useful.
