### ISSUE TITLE
Issue with gg_season() and unused argument from ggplot2.

### ISSUE THREAD

**Issue by william3031** [tidyverts/feasts#94]
I am trying to replicate the vignette: https://feasts.tidyverts.org/

```
library(feasts)
library(tsibbledata)
library(dplyr)
library(ggplot2)
library(lubridate)

aus_production %>% gg_season(Beer)
```

This produces the error: 

> Error in ggplot2::scale_x_date()$trans$breaks(limit, n = len) : unused argument (n = len)

The other functions seem to work. Also, I don't think this has been a problem in the past.

I have had this problem on a couple of different computers.

Here is the session info:
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

```

```
other attached packages:
[1] lubridate_1.7.4   ggplot2_3.3.0     dplyr_0.8.3       tsibbledata_0.1.0 feasts_0.1.2.9000 fabletools_0.1.2 
```

**Comment by mitchelloharawild** [comment]
Hi, thanks for your bug report!

> Please update the scales package to the latest CRAN version. I didn't
realise this version dependency before submitting the latest version to
CRAN, but it is correctly stated in the dev version.

#81

**Comment by william3031** [comment]
Great. Thanks for that. It works now.

**Comment by paulrougieux** [comment]
I had the same issue `unused argument (n = len)`with `gg_season`.

Re-installing the scale package fixes it thanks.
